### ISSUE TITLE
Dice Enhancement

### ISSUE THREAD

**Issue by drobati** [desert-planet/arrakis-hubot#125]
- [x] :game_die: Add modifiers for the rolls. (ie. +1, -3)
- [x] :game_die: Report only up to 10 rolls. Anything greater shows just the sum.
- [x] :game_die: Reduce extreme calculations. These are dice we are talking about.

**Comment by drobati** [comment]
Maybe I'll allow 1000 sided dice rolls. Thoughts?

**Comment by sshirokov** [comment]
Fixed in #127
